// 2: 3;
// 4: 7
// 6: 31
// 8: 55
// 12: 133 symbols

https://www.w3schools.com/charsets/ref_emoji.asp

const NOT_ENOUGH_ELEMENTS = (maxNr) => `Not enough elements. Limit is ${maxNr}`
const types = {
    TEXT: 'text',
    SVG: 'svg'
}

const lettersDigits = (nrOfElements) => {
    const elements = [
        {id: 0, contenet: 'A'},
        {id: 1, contenet: 'B'},
        {id: 2, contenet: 'C'},
        {id: 3, contenet: 'D'},
        {id: 4, contenet: 'E'},
        {id: 5, contenet: 'F'},
        {id: 6, contenet: 'G'},
        {id: 7, contenet: 'H'},
        {id: 8, contenet: 'I'},
        {id: 9, contenet: 'J'},
        {id: 10, contenet: 'K'},
        {id: 11, contenet: 'L'},
        {id: 12, contenet: 'M'},
        {id: 13, contenet: 'N'},
        {id: 14, contenet: 'O'},
        {id: 15, contenet: 'P'},
        {id: 16, contenet: 'Q'},
        {id: 17, contenet: 'R'},
        {id: 18, contenet: 'S'},
        {id: 19, contenet: 'T'},
        {id: 20, contenet: 'U'},
        {id: 21, contenet: 'V'},
        {id: 22, contenet: 'W'},
        {id: 23, contenet: 'X'},
        {id: 24, contenet: 'Y'},
        {id: 25, contenet: 'Z'},
        {id: 26, contenet: '1'},
        {id: 27, contenet: '2'},
        {id: 28, contenet: '3'},
        {id: 29, contenet: '4'},
        {id: 30, contenet: '5'},
        {id: 31, contenet: '6'},
        {id: 32, contenet: '7'},
        {id: 33, contenet: '8'},
        {id: 34, contenet: '9'},
        {id: 35, contenet: '!'},
        {id: 36, contenet: '@'},
        {id: 37, contenet: '#'},
        {id: 38, contenet: '$'},
        {id: 39, contenet: '%'},
        {id: 40, contenet: '&'},
        {id: 41, contenet: '*'},
        {id: 42, contenet: '+'},
        {id: 43, contenet: '-'},
        {id: 44, contenet: '?'},
        {id: 45, contenet: ':'},
        {id: 46, contenet: ';'},
        {id: 47, contenet: '/'},
        {id: 48, contenet: 'a'},
        {id: 49, contenet: 'b'},
        {id: 50, contenet: 'c'},
        {id: 51, contenet: 'd'},
        {id: 52, contenet: 'e'},
        {id: 53, contenet: 'f'},
        {id: 54, contenet: 'g'},
        {id: 55, contenet: 'h'},
    ];
    if (nrOfElements - 1 > elements.length) throw new Error(NOT_ENOUGH_ELEMENTS(elements.length));
    return {
        elements: elements.slice(0, nrOfElements - 1),
        type: types.TEXT,
        maxNr: elements.length,
    }
}

const topics = {
    N: 'nature',
    W: 'weather',
    A: 'astronomy',
    YS: 'year season',
    WI: 'winter',
    C: 'communicatoin',
    T: 'technology',
    G: 'gastronomy',
    M: 'music',
    S: 'sport',
    T: 'trawel',
    E: 'entertainment',
    AN: 'animal',
    O: 'outfit',
}

const htmlSymbols = (nrOfElements) => {
    const { A, W, N } = topics;
    const elements = [
        {id: 0,  name:'sun', contenet: '&#9728;', topics:[A, W, N]},
        {id: 1,  name:'cloud', contenet: '&#9729;', topics:[W, N]},
        {id: 2,  name:'umbrella', contenet: '&#9730;', topics:[W]},
        {id: 3,  name:'snowman', contenet: '&#9731;', topics:[w, YS, WI]},
        {id: 4,  name:'comet', contenet: '&#9732;', topics:[A]},
        {id: 5,  name:'star', contenet: '&#9734;', topics:[A]},
        {id: 6,  name:'phone', contenet: '&#9743;', topics:[C, T]},
        {id: 7,  name:'bewerage', contenet: '&#9749;', topics:[G]},
        {id: 8,  name:'shamrock', contenet: '&#9752;', topics:[N]},
        {id: 9,  name:'skull', contenet: '&#9760;', topics:[]},
        {id: 10, name:'heart', contenet: '&#9825;', topics:[]},
        {id: 11, name:'note', contenet: '&#9834;', topics:[]},
        {id: 12, name:'socker ball', contenet: '&#9917;', topics:[S]},
        {id: 13, name:'church', contenet: '&#9962;', topics:[]},
        {id: 14, name:'mountain', contenet: '&#9968;', topics:[N, T]},
        {id: 15, name:'fountain', contenet: '&#9970;', topics:[]},
        {id: 16, name:'ferry', contenet: '&#9972;', topics:[T]},
        {id: 17, name:'sailing', contenet: '&#9973;', topics:[S]},
        {id: 18, name:'ski', contenet: '&#9975;', topics:[S]},
        {id: 19, name:'ice skate', contenet: '&#9976;', topics:[S]},
        {id: 20, name:'tent', contenet: '&#9978;', topics:[T]},
        {id: 21, name:'fuel pump', contenet: '&#9981;', topics:[T]},
        {id: 22, name:'scissors', contenet: '&#9986;', topics:[]},
        {id: 23, name:'plane', contenet: '&#9992;', topics:[T]},
        {id: 24, name:'envelope', contenet: '&#9993;', topics:[C]},
        {id: 25, name:'raised hand', contenet: '&#9995;', topics:[C]},
        {id: 26, name:'pen', contenet: '&#9999;', topics:[C]},
        {id: 27, name:'city', contenet: '&#127747;', topics:[T]},
        {id: 28, name:'rainbow', contenet: '&#127752;', topics:[N, W]},
        {id: 29, name:'wave', contenet: '&#127754;', topics:[N, T]},
        {id: 30, name:'volcano', contenet: '&#127755;', topics:[N]},
        {id: 31, name:'earth', contenet: '&#127757;', topics:[A]},
        {id: 32, name:'moon', contenet: '&#127769;', topics:[A]},
        {id: 33, name:'thermometer', contenet: '&#127777;', topics:[W]},
        {id: 34, name:'thunder', contenet: '&#127785;', topics:[W]},
        {id: 35, name:'hod dog', contenet: '&#127789;', topics:[G]},
        {id: 36, name:'sandwidge', contenet: '&#127790;', topics:[G]},
        {id: 37, name:'tree', contenet: '&#127794;', topics:[N]},
        {id: 38, name:'cactus', contenet: '&#127797;', topics:[N, T]},
        {id: 39, name:'flower', contenet: '&#127803;', topics:[N]},
        {id: 40, name:'mushroom', contenet: '&#127812;', topics:[N, G]},
        {id: 41, name:'fruit', contenet: '&#127815;', topics:[G, N]},
        {id: 42, name:'banana', contenet: '&#127820;', topics:[G, N]},
        {id: 43, name:'pineaple', contenet: '&#127821;', topics:[G, N]},
        {id: 44, name:'pizza', contenet: '&#127829;', topics:[G]},
        {id: 45, name:'meal', contenet: '&#127835;', topics:[G]},
        {id: 46, name:'ice cream', contenet: '&#127846;', topics:[G]},
        {id: 47, name:'lollypop', contenet: '&#127853;', topics:[G]},
        {id: 48, name:'cake', contenet: '&#127856;', topics:[G]},
        {id: 49, name:'cocktail', contenet: '&#127865;', topics:[G]},
        {id: 50, name:'microphone', contenet: '&#127908;', topics:[M]},
        {id: 51, name:'movei camera', contenet: '&#127909;', topics:[]},
        {id: 52, name:'earphones', contenet: '&#127911;', topics:[M]},
        {id: 53, name:'palette', contenet: '&#127912;', topics:[]},
        {id: 54, name:'hat', contenet: '&#127913;', topics:[]},
        {id: 55, name:'circus', contenet: '&#127914;', topics:[E]},
        {id: 56, name:'theater masks', contenet: '&#127917;', topics:[E]},
        {id: 57, name:'game pad', contenet: '&#127918;', topics:[E]},
        {id: 58, name:'dice', contenet: '&#127922;', topics:[E]},
        {id: 59, name:'saxophone', contenet: '&#127927;', topics:[M]},
        {id: 60, name:'fiddle', contenet: '&#127931;', topics:[M]},
        {id: 61, name:'treble clef', contenet: '&#127932;', topics:[M]}, // klucz wiolinowy
        {id: 62, name:'tennis', contenet: '&#127934;', topics:[S]},
        {id: 63, name:'horse ride', contenet: '&#127943;', topics:[S]},
        {id: 64, name:'swim', contenet: '&#127946;', topics:[S]},
        {id: 65, name:'strongman', contenet: '&#127947;', topics:[S]},
        {id: 66, name:'golf', contenet: '&#127948;', topics:[S]},
        {id: 67, name:'motorcycle', contenet: '&#127949;', topics:[S, T]},
        {id: 68, name:'arena', contenet: '&#127967;', topics:[S]},
        {id: 69, name:'china', contenet: '&#127983;', topics:[T]},
        {id: 70, name:'arching', contenet: '&#127993;', topics:[S]},
        {id: 71, name:'rat', contenet: '&#128000;', topics:[AN]},
        {id: 72, name:'cow', contenet: '&#128004;', topics:[AN]},
        {id: 73, name:'tiger', contenet: '&#128005;', topics:[AN]},
        {id: 74, name:'rabbit', contenet: '&#128007;', topics:[AN]},
        {id: 75, name:'cat', contenet: '&#128008;', topics:[AN]},
        {id: 76, name:'fish', contenet: '&#128011;', topics:[AN]},
        {id: 77, name:'snail', contenet: '&#128012;', topics:[AN]},
        {id: 78, name:'snake', contenet: '&#128013;', topics:[AN]},
        {id: 79, name:'sheep', contenet: '&#128017;', topics:[AN]},
        {id: 80, name:'han', contenet: '&#128019;', topics:[AN]},
        {id: 81, name:'pig', contenet: '&#128022;', topics:[AN]},
        {id: 82, name:'elephant', contenet: '&#128024;', topics:[AN]},
        {id: 83, name:'octopus', contenet: '&#128025;', topics:[AN]},
        {id: 84, name:'shell', contenet: '&#128026;', topics:[AN]},
        {id: 85, name:'ant', contenet: '&#128028;', topics:[AN]},
        {id: 86, name:'bee', contenet: '&#128029;', topics:[AN]},
        {id: 87, name:'ladybird', contenet: '&#128030;', topics:[AN]},
        {id: 88, name:'turtle', contenet: '&#128034;', topics:[AN]},
        {id: 89, name:'bird', contenet: '&#128038;', topics:[AN]},
        {id: 90, name:'pinguin', contenet: '&#128039;', topics:[AN]},
        {id: 91, name:'coala', contenet: '&#128040;', topics:[AN]},
        {id: 92, name:'camel', contenet: '&#128042;', topics:[AN]},
        {id: 93, name:'crown', contenet: '&#128081;', topics:[AN]},
        {id: 94, name:'tie', contenet: '&#128084;', topics:[O]},
        {id: 95, name:'glasses', contenet: '&#128083;', topics:[O]},
        {id: 96, name:'shirt', contenet: '&#128085;', topics:[O]},
        {id: 97, name:'trouses', contenet: '&#128086;', topics:[O]},
        {id: 98, name:'dress', contenet: '&#128087;', topics:[O]},
        {id: 99, name:'underware', contenet: '&#128089;', topics:[O]},
        {id: 100, name:'bag', contenet: '&#128092;', topics:[O]},
        {id: 101, name:'shue' , contenet: '&#128095;', topics:[O]},
        {id: 102, name:'boy ', contenet: '&#128102;', topics:[O]},
        {id: 103, name:';', contenet: '', topics:[O]},

        // https://www.w3schools.com/charsets/ref_emoji.asp

    ];
    if (nrOfElements - 1 > elements.length) throw new Error(NOT_ENOUGH_ELEMENTS(elements.length));
    return {
        elements: elements.slice(0, nrOfElements - 1),
        type: types.TEXT,
        maxNr: elements.length,
    }
}